ftp:
  service:
    type: NodePort
  passive:
    resolveAddress: true
    address: ftp.example.org
  pvc:
    enabled: true
    setIncomingPermissions: true
  email_passwords:
    allowed:
    - allowed@example.org
  banner: "Hello and welcome!"
