language: python
services:
  - docker

before_install:
  - pip install docker-compose

script:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up -d
  - docker wait vsftpd-anonymous-upload-docker_ftpclient_1
  - docker exec vsftpd-anonymous-upload-docker_ftpserver_1 sh -c "cd incoming/test && sha1sum -c SHASUMS"

