vsftpd:
  image: vimagick/vsftpd
  ports:
    - "20:20"
    - "21:21"
    - "30000-30010:30000-30010"
  volumes:
    - ./vsftpd:/etc/vsftpd
    - ./ftp:/var/lib/ftp
  privileged: true
  restart: always
