apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vsftpd-anon
  labels:
    app: vsftpd-anon
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: vsftpd-anon
        release: {{ .Release.Name }}
    spec:
      {{- if and .Values.ftp.pvc.enabled .Values.ftp.pvc.setIncomingPermissions }}
      initContainers:
        - name: vsftpd-anon-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -x
            - -c
            - install -d -m {{ .Values.ftp.pvc.incomingPermissions }} -o ftp -g {{ .Values.ftp.pvc.incomingGroup }} /var/lib/ftp/incoming
          volumeMounts:
            - name: vsftp-incoming
              mountPath: /var/lib/ftp/incoming
      {{- end }}
      containers:
        - name: vsftpd-anon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- range $e := until (sub .Values.ftp.passivePorts.max .Values.ftp.passivePorts.min | add1 | int) }}
            - containerPort: {{ add $.Values.ftp.passivePorts.min . }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 21
          readinessProbe:
            tcpSocket:
              port: 21
        {{- if .Values.ftp.pvc.enabled }}
          volumeMounts:
            - name: vsftp-incoming
              mountPath: /var/lib/ftp/incoming
        {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.ftp.pvc.enabled }}
      volumes:
        - name: vsftp-incoming
          persistentVolumeClaim:
            claimName: vsftp-incoming
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
