apiVersion: v1
kind: Service
metadata:
  name: vsftpd-anon
  labels:
    app: vsftpd-anon
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: ftp
      {{- if and (contains "NodePort" .Values.service.type) .Values.service.externalPort }}
      nodePort: {{ .Values.service.externalPort }}
      {{- end }}
    {{- range $e := until (sub .Values.ftp.passivePorts.max .Values.ftp.passivePorts.min | add1 | int) }}
    {{- $port:= add $.Values.ftp.passivePorts.min . }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: ftp-pasv-{{ $port }}
      {{- if contains "NodePort" $.Values.service.type }}
      nodePort: {{ $port }}
      {{- end }}
    {{- end }}
  selector:
    app: vsftpd-anon
    release: {{ .Release.Name }}
