---
apiVersion: v1
kind: Service
metadata:
  name: vsftpd-anon
  labels:
    app: vsftpd-anon
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ftp.service.type }}
  ports:
    - port: {{ .Values.ftp.service.internalPort }}
      targetPort: {{ .Values.ftp.service.internalPort }}
      protocol: TCP
      name: ftp
      {{- if and (contains "NodePort" .Values.ftp.service.type) .Values.ftp.service.externalPort }}
      nodePort: {{ .Values.ftp.service.externalPort }}
      {{- end }}
    {{- range $e := until (sub .Values.ftp.passive.portMax .Values.ftp.passive.portMin | add1 | int) }}
    {{- $port:= add $.Values.ftp.passive.portMin . }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: ftp-pasv-{{ $port }}
      {{- if contains "NodePort" $.Values.ftp.service.type }}
      nodePort: {{ $port }}
      {{- end }}
    {{- end }}
  selector:
    app: vsftpd-anon
    release: {{ .Release.Name }}

---
{{ if and .Values.rsync.enabled .Values.ftp.pvc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rsync-ssh
  labels:
    app: rsync-ssh
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.rsync.service.type }}
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
      {{- if and (contains "NodePort" .Values.rsync.service.type) .Values.rsync.service.externalPort }}
      nodePort: {{ .Values.rsync.service.externalPort }}
      {{- end }}
  selector:
    app: vsftpd-anon
    release: {{ .Release.Name }}
{{- end }}
