apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
      {{- if and (contains "NodePort" .Values.service.type) .Values.service.externalNodePort }}
      nodePort: {{ .Values.service.externalNodePort }}
      {{- end }}
    {{- range $e := until (sub .Values.service.passMaxPort .Values.service.passMinPort | add1 | int) }}
    {{- $port:= add $.Values.service.passMinPort . }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $.Values.service.name }}-pasv-{{ $port }}
      {{- if contains "NodePort" $.Values.service.type }}
      nodePort: {{ $port }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}
