# Default values for helm.
replicaCount: 1
image:
  repository: manics/vsftpd-anonymous-upload
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 32021
  internalPort: 21
ftp:
  passive:
    portMin: 32022
    portMax: 32041
    resolveAddress: false
    address:
  pvc:
    enabled: false
    selector:
    storageClassName:
    accessModes:
    - ReadWriteOnce
    storage:
    setIncomingPermissions: false
    incomingPermissions: "u+wx,u-r,g+rwxs,o-rwx"
    incomingGroup: root
resources: {}
